#!/usr/bin/env python3
"""Generate the active shell code map. archive/map-v2 is intentionally excluded."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "CODEMAP.md"
SYMBOL = re.compile(
    r"^\s*pub\s+(?:struct|enum|fn|mod|const|type)\s+([A-Za-z_][A-Za-z0-9_]*)"
)


def rust_files() -> list[Path]:
    return sorted(path for path in (ROOT / "crates").glob("*/src/**/*.rs") if path.is_file())


def render() -> str:
    files = rust_files()
    lines = [
        "# MAPKEEPER Code Map",
        "",
        "_Auto-generated by `scripts/gen_codemap.py`. Active shell only; `archive/map-v2` is excluded._",
        "",
        "## Task -> first path",
        "",
        "- World identity and registry -> `crates/core/src/`",
        "- Projects and health API -> `crates/server/src/`",
        "- Five-mode shell UI -> `crates/web/index.html`",
        "- WASM bootstrap -> `crates/web/src/lib.rs`",
        "- Native launch -> `crates/desktop/src/lib.rs`",
        "- Archived map-v2 research -> `archive/map-v2/README.md` (never an active dependency)",
        "",
        f"## Active Rust files ({len(files)})",
        "",
    ]
    for path in files:
        relative = path.relative_to(ROOT).as_posix()
        lines.append(f"### `{relative}`")
        symbols = []
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            match = SYMBOL.match(line)
            if match:
                symbols.append(f"- L{number}: `{match.group(1)}`")
        lines.extend(symbols or ["- _(no public indexed symbols)_"])
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
