#!/usr/bin/env python3
"""
Generate docs/CODEMAP.md from current MAPKEEPER sources.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "CODEMAP.md"

SYMBOL_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("module", re.compile(r"^\s*pub\s+mod\s+([A-Za-z_][A-Za-z0-9_]*)\s*;")),
    ("struct", re.compile(r"^\s*pub\s+struct\s+([A-Za-z_][A-Za-z0-9_]*)")),
    ("enum", re.compile(r"^\s*pub\s+enum\s+([A-Za-z_][A-Za-z0-9_]*)")),
    ("trait", re.compile(r"^\s*pub\s+trait\s+([A-Za-z_][A-Za-z0-9_]*)")),
    ("type", re.compile(r"^\s*pub\s+type\s+([A-Za-z_][A-Za-z0-9_]*)")),
    ("const", re.compile(r"^\s*pub\s+const\s+([A-Za-z_][A-Za-z0-9_]*)")),
    ("fn", re.compile(r"^\s*pub(?:\([^)]*\))?\s+fn\s+([A-Za-z_][A-Za-z0-9_]*)")),
    ("impl", re.compile(r"^\s*impl(?:<[^>]+>)?\s+([A-Za-z_][A-Za-z0-9_]*)")),
]


@dataclass(frozen=True)
class Symbol:
    kind: str
    name: str
    line: int


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def discover_rust_files() -> list[Path]:
    files = sorted(ROOT.glob("crates/*/src/**/*.rs"))
    return [p for p in files if p.is_file()]


def extract_symbols(path: Path) -> list[Symbol]:
    symbols: list[Symbol] = []
    text = path.read_text(encoding="utf-8")
    for idx, line in enumerate(text.splitlines(), start=1):
        for kind, pattern in SYMBOL_PATTERNS:
            match = pattern.match(line)
            if match:
                symbols.append(Symbol(kind=kind, name=match.group(1), line=idx))
                break
    return symbols


def discover_top_level_files() -> list[Path]:
    picks = [
        ROOT / "Cargo.toml",
        ROOT / "README.md",
        ROOT / "STARTER_PACK.md",
        ROOT / "docs" / "CODEMAP-LITE.md",
    ]
    picks.extend(sorted((ROOT / "schemas").glob("*.json")))
    picks.extend(sorted((ROOT / ".github" / "workflows").glob("*.yml")))
    return [p for p in picks if p.exists()]


def task_routes() -> list[tuple[str, str]]:
    return [
        ("Core rules / geometry / layer model", "`crates/core/src/`"),
        ("HTTP API / world file I/O", "`crates/server/src/`"),
        ("CLI author flows and helpers", "`crates/cli/src/`"),
        ("Web UI / WASM editor", "`crates/web/src/`"),
        ("Desktop shell (Tauri)", "`crates/desktop/src/`"),
        ("Data contracts and fixtures", "`schemas/`, `fixtures/`"),
        ("World scaffold templates", "`toolchain/template/world/`"),
        ("CI workflows", "`.github/workflows/`"),
    ]


def render() -> str:
    rust_files = discover_rust_files()
    top_files = discover_top_level_files()
    crate_counts: dict[str, int] = {}
    symbol_map: list[tuple[Path, list[Symbol]]] = []

    for rust_file in rust_files:
        crate = rust_file.parts[rust_file.parts.index("crates") + 1]
        crate_counts[crate] = crate_counts.get(crate, 0) + 1
        symbol_map.append((rust_file, extract_symbols(rust_file)))

    lines: list[str] = []
    lines.append("# MAPKEEPER Code Map")
    lines.append("")
    lines.append("_Auto-generated by `scripts/gen_codemap.py`. Do not edit by hand._")
    lines.append("")
    lines.append("## Task -> first path")
    lines.append("")
    for task, route in task_routes():
        lines.append(f"- {task} -> {route}")
    lines.append("")
    lines.append("## Workspace overview")
    lines.append("")
    lines.append(
        f"- Rust source files: **{len(rust_files)}** (`crates/*/src/**/*.rs`)"
    )
    lines.append(
        "- Crate module counts: "
        + ", ".join(
            f"`{crate}`={count}" for crate, count in sorted(crate_counts.items())
        )
    )
    lines.append(f"- Top-level tracked files: **{len(top_files)}**")
    lines.append("")
    lines.append("## Top-level files")
    lines.append("")
    for top_file in top_files:
        lines.append(f"- `{rel(top_file)}`")
    lines.append("")
    lines.append("## Rust symbol index")
    lines.append("")
    lines.append("Symbols include public modules/types/functions and impl blocks.")
    lines.append("")

    for rust_file, symbols in symbol_map:
        lines.append(f"### `{rel(rust_file)}`")
        if not symbols:
            lines.append("- _(no indexed symbols)_")
            lines.append("")
            continue
        for symbol in symbols:
            lines.append(f"- L{symbol.line}: `{symbol.kind}` `{symbol.name}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    content = render()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {rel(OUTPUT)}")


if __name__ == "__main__":
    main()
